"""robots.txt, sitemap.xml, ads.txt, manifest.webmanifest, favicon.svg and assets/pubs.js."""
import json

from . import fmt
from .data import updated
from .fmt import esc


def robots(D):
    u = D["cfg"]["site_url"].rstrip("/")
    return f"User-agent: *\nAllow: /\nDisallow: /search/\nSitemap: {u}/sitemap.xml\n"


def sitemap(D, routes):
    u = D["cfg"]["site_url"].rstrip("/")
    rows = [f"<url><loc>{esc(u + r.path)}</loc><lastmod>{updated(D, r.dates) if r.dates else D['dates']['meta']}</lastmod></url>"
            for r in routes if r.index == "I"]
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(rows) + "\n</urlset>\n")


def ads_txt(D):
    c = (D["cfg"].get("adsense_client") or "").strip()
    if not c:
        return None
    return f"google.com, {c.removeprefix('ca-')}, DIRECT, f08c47fec0942fa0\n"


def manifest(D):
    return json.dumps({
        "name": "NK15068", "short_name": "NK15068", "start_url": "./", "scope": "./", "display": "minimal-ui",
        "theme_color": "#8a1c2b", "background_color": "#ffffff",
        "icons": [{"src": "favicon.svg", "sizes": "any", "type": "image/svg+xml"}],
        "shortcuts": [{"name": "Lost pets", "url": "lost-pets/"}, {"name": "Phone numbers", "url": "numbers/"}],
    }, indent=1, ensure_ascii=False) + "\n"


def favicon():
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">'
            '<rect width="32" height="32" fill="#8a1c2b"/>'
            '<text x="16" y="21.5" text-anchor="middle" font-family="Georgia, serif" font-weight="700" '
            'font-size="15" fill="#fff">NK</text></svg>\n')


def pubs_js():
    return ("/* generated by scripts/build_pages.py from nkpages/fmt.py PUBS */\n"
            f"window.NK_PUBS = {json.dumps(fmt.PUBS, ensure_ascii=False, sort_keys=True)};\n")
