"""The frame around every page: <head>, masthead, section bar, More menu, footer, scripts, ad slots and JSON-LD.

Page functions return either the <main> body as a string or a dict:
  {"body": str, "crumbs": [(label, "/path/" or None), …], "jsonld": [dict, …], "og_title": str,
   "og_image": absolute URL, "head": extra <head> html, "updated": ISO date overriding the route's data date}
Ad positions are marked in the body with <!--AD:mid--> and <!--AD:end-->; page_html() decides whether a slot
goes there (see ad_slot()).
"""
import json
import re

from . import fmt
from .data import updated as data_updated
from .fmt import esc

BANNER = "<!-- generated by scripts/build_pages.py; edit the templates, not this file -->"
FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">\n'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
         '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,'
         '400..800;1,6..72,400..600&family=Radio+Canada:ital,wdth,wght@0,75..100,400..700;1,75..100,400..600'
         '&display=swap">')
THEME_BOOT = '<script>try{var t=localStorage.getItem("nk-theme");if(t)document.documentElement.dataset.theme=t}catch(e){}</script>'
LEGACY = ('<script>(function(){var m={map:"map/",news:"news/",pets:"lost-pets/",towns:"towns/",safety:"crime/",'
          'story:"history/",eat:"eat/",people:"history/people/",directory:"directory/",sources:"sources/"};'
          'var h=location.hash.slice(1);if(m[h])location.replace(m[h]);})();</script>')
SHELTER = ("Animal Protectors", "724-339-7388")
ADSENSE_RE = re.compile(r"^ca-pub-\d{16}$")
AD_MARK = re.compile(r"<!--AD:(mid|end)-->")
AD_MIN_WORDS = 250


# --------------------------------------------------------------------------- links


def rel(frm, to):
    """Link from route `frm` to site path `to` ("/lost-pets/", "/", "data/x.json", "#id")."""
    if to.startswith(("#", "http:", "https:", "mailto:", "tel:")):
        return to
    root = frm.root if hasattr(frm, "root") else frm
    t = to.lstrip("/")
    return (root + t) or "./"


def correction_url(D):
    return f"https://github.com/{D['cfg']['repo']}/issues/new?template=correction.yml"


def issues_url(D):
    return f"https://github.com/{D['cfg']['repo']}/issues"


def ads_on(D):
    return bool((D["cfg"].get("adsense_client") or "").strip())


# --------------------------------------------------------------------------- masthead, bar, More, footer


def _search_form(R, fid, cls="sitesearch", placeholder="Street, business, number or topic"):
    return (f'<form class="{cls}" role="search" action="{rel(R, "/search/")}" method="get">'
            f'<label for="{fid}">Search 15068</label><span class="sf-row">'
            f'<input id="{fid}" name="q" type="search" placeholder="{esc(placeholder)}" autocomplete="off">'
            f'<button type="submit">Search</button></span></form>')


def _utility(D, R, upd, long_date):
    when = fmt.ap_long(upd) if long_date else fmt.ap_date(upd)
    left = f'<span id="u-built">Updated {when} · <a href="{rel(R, "/whats-new/")}">What&rsquo;s new ›</a></span>'
    if R.page.startswith("lost-pets"):
        right = 'Emergency? Call <a class="tel-inline" href="tel:911">911</a>'
    else:
        n, ph = SHELTER
        right = (f'Lost or found a pet? {n}: <a class="tel-inline" href="{fmt.tel(ph)[0][1]}">{ph}</a>')
    return f'<div class="utility"><div class="page">{left}<span class="u-right">{right}</span></div></div>'


def masthead(D, R, upd):
    if R.page == "home":
        return ('<header class="masthead home">' + _utility(D, R, upd, True) +
                '<div class="page flag"><a class="nameplate" href="./">NK15068</a>'
                '<p class="tagline">New Kensington · Arnold · Lower Burrell</p>'
                + _search_form(R, "hq", "ear sitesearch") + '</div></header>')
    util = "" if R.page in ("map", "map3d") else _utility(D, R, upd, False).replace('class="utility"', 'class="utility w720"', 1)
    return ('<header class="masthead inner">' + util +
            f'<div class="page flag compact"><a class="nameplate" href="{rel(R, "/")}">NK15068</a>'
            '<p class="tagline"><span>New Kensington · Arnold</span> <span>Lower Burrell · ZIP 15068</span></p>'
            + ("" if R.page in ("map", "map3d") else _search_form(R, "hq", "ear sitesearch w720")) + '</div></header>')


BAR = [  # (nav key, path, label html, css class, aria-label)
    ("lost-pets", "/lost-pets/", "Lost pets", "", None),
    ("numbers", "/numbers/", '<span class="lw">Phone numbers</span><span class="ln">Call</span>', "", "Phone numbers"),
    ("calendar", "/calendar/", "Calendar", "", None),
    ("crime", "/crime/", "Crime", "", None),
    ("map", "/map/", "Map", "", None),
    ("towns", "/towns/", "Towns", "w720", None),
    ("news", "/news/", "News", "w960", None),
    ("history", "/history/", "History", "w960", None),
    ("eat", "/eat/", "Eat &amp; drink", "w960", None),
]


def secbar(D, R):
    links = []
    for key, path, label, cls, aria in BAR:
        a = [f'href="{rel(R, path)}"', f'data-nav="{key}"']
        if cls:
            a.append(f'class="{cls}"')
        if aria:
            a.append(f'aria-label="{aria}"')
        if R.nav == key:
            a.append('aria-current="page"')
        links.append(f'<a {" ".join(a)}>{label}</a>')
    return ('<nav class="secbar" aria-label="Sections"><div class="page"><div class="links">' + "".join(links) +
            '</div>' + more(D, R) +
            '<button type="button" class="theme-btn w720" data-theme-toggle>Dark</button></div></nav>')


def more(D, R):
    L = lambda p, t, c="": f'<a href="{rel(R, p)}"{f" class={chr(34)}{c}{chr(34)}" if c else ""}>{t}</a>'
    rows = [
        ('m-only', _search_form(R, "mq")),
        ("", L("/", "Front page")),
        ("", "Towns: " + " · ".join([L("/towns/new-kensington/", "New Kensington"), L("/towns/arnold/", "Arnold"),
                                     L("/towns/lower-burrell/", "Lower Burrell")]) + " · " + L("/towns/", "All three towns")),
        ("no960", L("/news/", "News")),
        ("", L("/history/", "History", "no960") + '<span class="no960"> · </span>' + L("/history/people/", "Notable people")),
        ("no960", L("/eat/", "Eat &amp; drink")),
        ("", L("/crime/blotter/", "Police blotter") + " · " + L("/crashes/", "Serious crashes")),
        ("", L("/poster/", "Map poster") + " · " + L("/map/3d/", "3D view")),
        ("", L("/directory/", "Places and streets A to Z")),
        ("", L("/whats-new/", "What&rsquo;s new")),
        ("", " · ".join([L("/about/", "About"), L("/privacy/", "Privacy"), L("/contact/", "Contact"),
                         L("/sources/", "Sources")])),
        ("m-only", '<button type="button" class="text-btn" data-theme-toggle>Dark theme</button>'),
    ]
    lis = "".join(f'<li{f" class={chr(34)}{c}{chr(34)}" if c else ""}>{h}</li>' for c, h in rows)
    return f'<details class="more"><summary>More</summary><div class="more-sheet"><ul>{lis}</ul></div></details>'


INDEX_COLS = [
    ("Help", [("/lost-pets/", "Lost or found a pet"), ("/numbers/", "Phone numbers"), ("/calendar/", "Calendar"),
              ("/map/", "Map"), ("/directory/", "Places and streets A to Z"), ("/poster/", "Map poster")]),
    ("Answers", [("/crime/", "Crime and safety"), ("/crime/new-kensington/", "New Kensington police"),
                 ("/crime/arnold/", "Arnold police"), ("/crime/lower-burrell/", "Lower Burrell police"),
                 ("/crime/blotter/", "Police blotter"), ("/crashes/", "Serious crashes"),
                 ("/towns/", "The three towns"), ("/towns/new-kensington/", "New Kensington"),
                 ("/towns/arnold/", "Arnold"), ("/towns/lower-burrell/", "Lower Burrell")]),
    ("Reference", [("/news/", "News"), ("/history/", "History"), ("/history/people/", "Notable people"),
                   ("/eat/", "Eat and drink"), ("/whats-new/", "What's new"), ("/about/", "About"),
                   ("/privacy/", "Privacy"), ("/contact/", "Contact"), ("/sources/", "Sources")]),
]


def footer(D, R, upd):
    cols = "".join(f'<div><h2 class="fh">{h}</h2><ul>' +
                   "".join(f'<li><a href="{rel(R, p)}">{esc(t)}</a></li>' for p, t in items) + "</ul></div>"
                   for h, items in INDEX_COLS)
    return ('<footer class="site-foot"><div class="page">'
            f'<nav id="site-index" aria-label="All pages">{cols}</nav>'
            f'<p class="foot-upd">Updated {fmt.ap_date(upd)} · <a href="{rel(R, "/whats-new/")}">What&rsquo;s new ›</a></p>'
            f'<p class="foot-links"><a href="{rel(R, "/about/")}">About</a> · <a href="{rel(R, "/privacy/")}">Privacy</a> · '
            f'<a href="{rel(R, "/contact/")}">Contact</a> · <a href="{rel(R, "/sources/")}">Sources</a> · '
            f'<a href="{esc(correction_url(D))}">Report a correction ›</a></p>'
            '<p class="foot-attrib">Map data © OpenStreetMap contributors, Overture Maps Foundation</p>'
            '</div></footer>')


def crumbs_html(R, crumbs):
    """Visible breadcrumbs only when there is a parent to go back to; a lone crumb would read as a label over the
    H1 (the JSON-LD BreadcrumbList still carries it)."""
    if not crumbs or not any(path for _, path in crumbs):
        return ""
    parts = []
    for label, path in crumbs:
        parts.append(f'<a href="{rel(R, path)}">{esc(label)}</a>' if path else f'<span aria-current="page">{esc(label)}</span>')
    return '<nav class="crumbs page" aria-label="Breadcrumb">' + " › ".join(parts) + "</nav>"


# --------------------------------------------------------------------------- ads


def head_ads(D, R):
    if not ads_on(D) or R.ads != "C":
        return ""
    c = esc(D["cfg"]["adsense_client"].strip())
    return (f'<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={c}" '
            'crossorigin="anonymous"></script>')


def ad_slot(D, R, which):
    slot = ((D["cfg"].get("adsense_slots") or {}).get(which) or "").strip()
    if not ads_on(D) or R.ads != "C" or not slot:
        return ""
    c = esc(D["cfg"]["adsense_client"].strip())
    return ('<aside class="adslot" aria-label="Advertisement"><p class="adslot-label">Advertisement</p>'
            f'<ins class="adsbygoogle" style="display:block" data-ad-client="{c}" data-ad-slot="{esc(slot)}" '
            'data-ad-format="auto" data-full-width-responsive="true"></ins>'
            '<script>(adsbygoogle = window.adsbygoogle || []).push({});</script></aside>')


def place_ads(D, R, main):
    """Replace <!--AD:mid|end--> markers: a slot only when configured, on a C route, after >= 250 words of main text
    and after every data-keep-above element; otherwise nothing."""
    out, pos = [], 0
    for m in AD_MARK.finditer(main):
        out.append(main[pos:m.start()])
        before, after = main[:m.start()], main[m.end():]
        ok = fmt.words(before) >= AD_MIN_WORDS and "data-keep-above" not in after
        out.append(ad_slot(D, R, m.group(1)) if ok else "")
        pos = m.end()
    out.append(main[pos:])
    return "".join(out)


# --------------------------------------------------------------------------- JSON-LD


def jsonld_tag(obj):
    return f'<script type="application/ld+json">{fmt.json_script(obj)}</script>'


def site_url(D):
    return D["cfg"]["site_url"].rstrip("/")


def jsonld_website(D):
    u = site_url(D)
    return {"@context": "https://schema.org", "@type": "WebSite", "name": "NK15068", "url": u + "/",
            "potentialAction": {"@type": "SearchAction", "target": u + "/search/?q={search_term_string}",
                                "query-input": "required name=search_term_string"}}


def jsonld_breadcrumbs(D, R, crumbs):
    u = site_url(D)
    items = [("NK15068", "/")] + [(l, p or R.path) for l, p in (crumbs or [(short_title(R), None)])]
    return {"@context": "https://schema.org", "@type": "BreadcrumbList",
            "itemListElement": [{"@type": "ListItem", "position": i + 1, "name": l, "item": u + p}
                                for i, (l, p) in enumerate(items)]}


def short_title(R):
    return R.title.removesuffix(" · NK15068")


# --------------------------------------------------------------------------- the page


def script_tags(R):
    from .routes import SCRIPTS
    out = []
    for k in R.scripts:
        src = SCRIPTS[k]
        out.append(f'<script src="{src if src.startswith("http") else rel(R, src)}"></script>')
    return "\n".join(out)


def page_html(D, R, result):
    res = {"body": result} if isinstance(result, str) else dict(result)
    upd = res.get("updated") or data_updated(D, R.dates)
    su = site_url(D)
    canon = su + ("/404.html" if R.path == "/404.html" else R.path)
    robots = {"N": '<meta name="robots" content="noindex">', "NF": '<meta name="robots" content="noindex,follow">'}.get(R.index, "")
    og_title = res.get("og_title") or short_title(R)
    og_img = res.get("og_image") or (su + "/img/og-15068.png" if (D["site"] / "img" / "og-15068.png").exists() else "")
    lds = []
    if R.page == "home":
        lds.append(jsonld_website(D))
    elif R.path != "/404.html":
        lds.append(jsonld_breadcrumbs(D, R, res.get("crumbs")))
    lds += res.get("jsonld") or []
    root = R.root
    desc = f'<meta name="description" content="{esc(R.desc)}">\n' if R.desc else ""
    head = [
        BANNER, "<!doctype html>",
        f'<html lang="en" data-page="{R.page}" data-root="{root}">', "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
        f"<title>{esc(R.title)}</title>",
        desc + f'<link rel="canonical" href="{esc(canon)}">',
    ]
    if robots:
        head.append(robots)
    head += [
        '<meta property="og:type" content="website"><meta property="og:site_name" content="NK15068">',
        f'<meta property="og:title" content="{esc(og_title)}">' +
        (f'<meta property="og:description" content="{esc(R.desc)}">' if R.desc else ""),
        f'<meta property="og:url" content="{esc(canon)}">' +
        (f'<meta property="og:image" content="{esc(og_img)}">' if og_img else ""),
        '<meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#8a1c2b">',
        f'<link rel="icon" href="{root}favicon.svg" type="image/svg+xml"><link rel="manifest" href="{root}manifest.webmanifest">',
        THEME_BOOT, FONTS, f'<link rel="stylesheet" href="{root}assets/nk.css">',
    ]
    if R.page == "home":
        head.append(LEGACY)
    if res.get("head"):
        head.append(res["head"])
    if D.get("board") is not None and "pets" in R.scripts:  # pets.js reads data/pets-board.json only when it exists
        head.append(f'<meta name="nk-pets-snapshot" content="{esc(D["board"].get("fetched") or "")}">')
    ha = head_ads(D, R)
    if ha:
        head.append(ha)
    head += [jsonld_tag(o) for o in lds]
    head.append("</head>")
    main = crumbs_html(R, [c for c in (res.get("crumbs") or [])]) + res["body"]
    main = place_ads(D, R, main)
    no_foot = R.page in ("map", "map3d")
    body = [
        "<body>", '<a class="skip" href="#main">Skip to content</a>',
        masthead(D, R, upd), secbar(D, R),
        f'<main id="main"{res.get("main_attrs", "")}>{main}</main>',
        "" if no_foot else footer(D, R, upd),
        script_tags(R), "</body></html>", "",
    ]
    return "\n".join(head + [b for b in body if b])
