"""Site-wide rules for the generated pages (every route, head tags, SEO files, ads, privacy, links, copy rules).

Page-specific checks live next to each group of pages in tests/test_pages_*.py.
"""
import json
import re
import subprocess
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from pagebuild import ROOT, SCRIPT, build, files, html_of, main_words, parse  # noqa: E402

from nkpages import routes as NR  # noqa: E402

ROUTES = NR.ROUTES
PATHS = [r.path for r in ROUTES]
C_ROUTES = {r.path for r in ROUTES if r.ads == "C"}
INTERNAL = re.compile(r"WebSearch|WebFetch|egress|search summar|\bverify\b|_meta|not reachable|could not be retrieved|"
                      r"independent researchers|month approximate", re.I)
ARROWS = re.compile("[→←↓↑▲▼▾]")
PHONE = re.compile(r"\b\d{3}-\d{3}-\d{4}\b")
HOUSE = re.compile(r"\b(\d{2,5})\s+(?:[NSEW]\.?\s+)?(?:\d+(?:st|nd|rd|th)|[A-Z][a-z]+)\s+"
                   r"(?:Street|St|Avenue|Ave|Road|Rd|Drive|Dr|Boulevard|Blvd|Lane|Ln|Way|Court|Ct|Alley|Place|Pl)\b")
WORDS = {400: ["/crime/new-kensington/", "/crime/arnold/", "/crime/lower-burrell/", "/crashes/", "/towns/new-kensington/",
               "/towns/arnold/", "/towns/lower-burrell/", "/history/", "/lost-pets/"],
         300: ["/crime/", "/numbers/", "/calendar/", "/news/", "/eat/", "/towns/", "/about/", "/privacy/", "/sources/",
               "/history/people/"],
         200: ["/"]}


# The page tests run once site/ has been generated (site/data/build.json exists), or while building with
# NK_KEEP_GOING=1, like SafetyData in test_data.py waits for safety.json.
GENERATED = (ROOT / "site" / "data" / "build.json").exists() or bool(__import__("os").environ.get("NK_KEEP_GOING"))
needs_site = unittest.skipUnless(GENERATED, "site/ has not been generated yet (run scripts/build_pages.py)")


def generated_texts(out, exts=(".html", ".xml", ".json", ".txt", ".webmanifest")):
    for p in sorted(out.rglob("*")):
        if p.is_file() and not p.is_symlink() and p.suffix in exts:
            yield p, p.read_text(encoding="utf-8")


@needs_site
class Pages(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.out = build("default")
        cls.pages = {}
        for r in ROUTES:
            p = cls.out / r.file
            if p.exists():
                cls.pages[r.path] = p.read_text(encoding="utf-8")

    def test_routes_exist(self):
        missing = [p for p in PATHS if p not in self.pages]
        self.assertEqual(missing, [], "routes without a page")
        self.assertTrue((self.out / "404.html").exists())

    def test_banner(self):
        for path, t in self.pages.items():
            self.assertTrue(t.startswith("<!-- generated by scripts/build_pages.py"), path)

    def test_head(self):
        titles = {}
        for r in ROUTES:
            t = self.pages.get(r.path)
            if t is None:
                continue
            with self.subTest(route=r.path):
                p = parse(t)
                self.assertEqual(len(p.h1), 1, f"{r.path}: {len(p.h1)} <h1>")
                title = re.search(r"<title>(.*?)</title>", t, re.S).group(1)
                self.assertNotIn(title, titles, f"duplicate title with {titles.get(title)}")
                titles[title] = r.path
                self.assertIn('<html lang="en"', t)
                if r.path != "/404.html":
                    d = re.search(r'<meta name="description" content="([^"]*)"', t)
                    self.assertTrue(d, "no meta description")
                    n = len(__import__("html").unescape(d.group(1)))
                    self.assertTrue(50 <= n <= 170, f"description length {n}")
                    canon = re.search(r'<link rel="canonical" href="([^"]+)"', t).group(1)
                    self.assertEqual(canon, "https://nk15068.com" + r.path)
                robots = re.search(r'<meta name="robots" content="([^"]+)"', t)
                want = {"N": "noindex", "NF": "noindex,follow"}.get(r.index)
                self.assertEqual(robots.group(1) if robots else None, want)

    def test_no_internal_strings(self):
        for p, t in generated_texts(self.out):
            if p.name in ("build.json", "meta.json"):
                continue
            m = INTERNAL.search(t)
            self.assertIsNone(m, f"{p.relative_to(self.out)}: {m and t[max(0, m.start() - 60):m.end() + 60]!r}")

    def test_words_without_js(self):
        for floor, paths in WORDS.items():
            for path in paths:
                if path not in self.pages:
                    continue
                with self.subTest(route=path):
                    self.assertGreaterEqual(main_words(self.pages[path]), floor)

    def test_no_loading_text(self):
        for path, t in self.pages.items():
            text = " ".join(parse(t).main_text)
            self.assertNotRegex(text, r"\bLoading\b", path)

    def test_tel_links(self):
        known = set()
        for f in ("data/research/civic.json", "data/research/pets.json", "site/data/places.json", "site/data/safety.json"):
            known |= {re.sub(r"\D", "", m) for m in re.findall(r"\(?\d{3}\)?[-. ]?\d{3}[-. ]\d{4}", (ROOT / f).read_text())}
        for path, t in self.pages.items():
            for href in re.findall(r'href="(tel:[^"]*)"', t):
                with self.subTest(route=path, href=href):
                    self.assertRegex(href, r"^tel:(\+1\d{10}|911)$")
                    if href != "tel:911":
                        self.assertIn(href[-10:], known, "number not in the data")
        for path in ("/", "/numbers/", "/lost-pets/"):
            if path not in self.pages:
                continue
            t = re.sub(r"<(script|style|template)\b.*?</\1>", " ", self.pages[path], flags=re.S)
            bare = re.sub(r'<a [^>]*href="tel:[^"]*"[^>]*>.*?</a>', " ", t, flags=re.S)
            bare = re.sub(r"<[^>]+>", " ", bare)
            self.assertEqual(PHONE.findall(bare), [], f"{path}: phone numbers that aren't tap-to-call")

    def test_privacy_rules(self):
        for out in (self.out, build("snapshot")):
            for p in files(out):
                t = p.read_text(encoding="utf-8")
                blocks = re.findall(r'<article class="entry".*?</article>', t, re.S)
                blocks += re.findall(r'<(?:article|li|div) class="listing\b.*?</(?:article|li|div)>', t, re.S)
                for b in blocks:
                    text = re.sub(r"<[^>]+>", " ", b)
                    for n in HOUSE.findall(text):
                        self.assertEqual(int(n) % 100, 0, f"{p.relative_to(out)}: house number in {text[:160]!r}")
        s = json.loads((ROOT / "site/data/safety.json").read_text())
        self.assertFalse([i for i in s["incidents"] if i["k"] in {"sexual_assault", "rape", "sex_offense"}])

    def test_ads_off(self):
        for p, t in generated_texts(self.out, (".html", ".js", ".css", ".txt")):
            for needle in ("adsbygoogle", "pagead2", 'class="adslot'):
                self.assertNotIn(needle, t, p.relative_to(self.out))
        self.assertFalse((self.out / "ads.txt").exists())

    def test_seo_files(self):
        robots = (self.out / "robots.txt").read_text()
        self.assertIn("Sitemap: https://nk15068.com/sitemap.xml", robots)
        self.assertIn("Disallow: /search/", robots)
        sm = (self.out / "sitemap.xml").read_text()
        locs = re.findall(r"<loc>https://nk15068.com(.*?)</loc>", sm)
        self.assertEqual(sorted(locs), sorted(r.path for r in ROUTES if r.index == "I"))
        for d in re.findall(r"<lastmod>(.*?)</lastmod>", sm):
            self.assertRegex(d, r"^\d{4}-\d\d-\d\d$")
        m = json.loads((self.out / "manifest.webmanifest").read_text())
        self.assertEqual([s["url"] for s in m["shortcuts"]], ["lost-pets/", "numbers/"])

    def test_links_resolve(self):
        for r in ROUTES:
            t = self.pages.get(r.path)
            if t is None:
                continue
            base = (self.out / r.file).parent
            p = parse(t)
            for u in p.links + p.srcs:
                if re.match(r"^(https?:|mailto:|tel:|#|data:|javascript:)", u) or not u:
                    continue
                u = u.split("#")[0].split("?")[0].split(" ")[0]
                if not u:
                    continue
                tgt = (self.out / u.lstrip("/")).resolve() if u.startswith("/") else (base / u).resolve()
                if u.endswith("/") or tgt.is_dir():
                    tgt = tgt / "index.html"
                with self.subTest(route=r.path, href=u):
                    self.assertTrue(tgt.exists(), f"{r.path} links to missing {u}")

    def test_three_only_on_3d(self):
        for path, t in self.pages.items():
            has = "three.min.js" in t
            self.assertEqual(has, path == "/map/3d/", path)

    def test_classnames(self):
        for path, t in self.pages.items():
            for cls in re.findall(r'class="([^"]*)"', t):
                self.assertNotRegex(cls, r"(^|\s)ads?(\s|$|-)", f"{path}: class {cls!r}")
        for f in ("site/assets/nk.css", "site/assets/app.js"):
            p = self.out / f.removeprefix("site/")
            if p.exists():
                t = p.read_text()
                bad = [m for m in re.findall(r"\.ads?\b[\w-]*", t) if not m.startswith(".adslot")]
                self.assertEqual(bad, [], f)

    def test_no_arrows(self):
        for path, t in self.pages.items():
            text = " ".join(parse(t).all_text)
            self.assertIsNone(ARROWS.search(text), f"{path}: {ARROWS.findall(text)}")

    def test_scripts_order(self):
        for path, t in self.pages.items():
            srcs = re.findall(r'<script src="([^"]+)"', t)
            names = [s.rsplit("/", 1)[-1] for s in srcs]
            with self.subTest(route=path):
                self.assertEqual(names[-1], "app.js")
                self.assertLess(names.index("pubs.js"), names.index("app.js"))

    def test_legacy_map(self):
        t = self.pages.get("/")
        if t is None:
            self.skipTest("home not built")
        for k in ("map", "news", "pets", "towns", "safety", "story", "eat", "people", "directory", "sources"):
            self.assertRegex(t, rf'\b{k}:"')


@needs_site
class Ads(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.out = build("ads")

    def test_ads_txt(self):
        self.assertEqual((self.out / "ads.txt").read_text(),
                         "google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0\n")

    def test_slots_only_on_c_routes_and_after_keep_above(self):
        for r in ROUTES:
            p = self.out / r.file
            if not p.exists():
                continue
            t = p.read_text(encoding="utf-8")
            n = t.count('class="adslot"')
            with self.subTest(route=r.path):
                if r.path not in C_ROUTES:
                    self.assertEqual(n, 0)
                    self.assertNotIn("pagead2", t)
                    continue
                self.assertLessEqual(n, 2)
                main = t[t.index("<main"):t.index("</main>")]
                first = main.find('class="adslot"')
                if first < 0:
                    continue
                self.assertNotIn("data-keep-above", main[first:])
                self.assertGreaterEqual(main_words(main[:first] + "</main>"), 250)

    def test_ads_need_owner(self):
        import tempfile
        cfg = json.loads((ROOT / "tests/fixtures/site-ads.json").read_text())
        cfg["owner_name"] = ""
        with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
            json.dump(cfg, f)
        r = subprocess.run([sys.executable, str(SCRIPT), "--config", f.name, "--out", tempfile.mkdtemp()],
                           capture_output=True, text=True)
        self.assertEqual(r.returncode, 2, r.stderr)
        self.assertIn("About must name who runs the site", r.stderr)


@needs_site
class Committed(unittest.TestCase):
    def test_check_clean(self):
        if not (ROOT / "site/data/build.json").exists():
            self.skipTest("site/ has not been generated yet")
        r = subprocess.run([sys.executable, str(SCRIPT), "--check"], capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_synced_research_matches(self):
        from nkpages.data import public_copy
        for k in ("civic", "history", "pets"):
            src = json.loads((ROOT / f"data/research/{k}.json").read_text())
            pub = (ROOT / f"site/data/{k}.json").read_text()
            self.assertEqual(pub, json.dumps(public_copy(src), separators=(",", ":"), ensure_ascii=False), k)
            self.assertIsNone(INTERNAL.search(pub), f"{k}.json: {INTERNAL.search(pub)}")


if __name__ == "__main__":
    unittest.main()
