"""Strict Wavefront OBJ subset: the interchange for NK component geometry.

NK geometry stays in its sealed release; the operator exports one component
per OBJ locally. Accepted: `v x y z`, `f a b c ...` (1-based or negative
indices, `a/b/c` forms; polygons are fan-triangulated), `o`/`g`/`usemtl`
(material names are kept per triangle), comments and blank lines. Anything
else (curves, `vp`, lines) is rejected rather than skipped.
"""
import math
from dataclasses import dataclass, field

from .errors import FormatError

MAX_VERTICES = 2_000_000
MAX_TRIANGLES = 4_000_000
IGNORED = ('vt', 'vn', 's', 'mtllib', 'o', 'g')


@dataclass
class Mesh:
    vertices: list = field(default_factory=list)     # [(x, y, z)]
    triangles: list = field(default_factory=list)    # [(i, j, k)] 0-based
    materials: list = field(default_factory=list)    # material per triangle

    def bounds(self):
        if not self.vertices:
            raise FormatError('mesh has no vertices')
        xs, ys, zs = zip(*self.vertices)
        return (min(xs), min(ys), min(zs)), (max(xs), max(ys), max(zs))


def _index(tok, n, line_no):
    try:
        i = int(tok.split('/')[0])
    except ValueError:
        raise FormatError('line %d: bad face index %r' % (line_no, tok)) from None
    i = i - 1 if i > 0 else n + i
    if not 0 <= i < n:
        raise FormatError('line %d: face index %r out of range' % (line_no, tok))
    return i


def parse_obj(text):
    mesh, material = Mesh(), None
    for no, raw in enumerate(text.splitlines(), 1):
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        key, *rest = line.split()
        if key == 'v':
            if len(rest) not in (3, 4, 6, 7):
                raise FormatError('line %d: vertex needs 3 coordinates' % no)
            try:
                xyz = tuple(float(t) for t in rest[:3])
            except ValueError:
                raise FormatError('line %d: bad vertex' % no) from None
            if not all(math.isfinite(c) for c in xyz):
                raise FormatError('line %d: non-finite vertex' % no)
            mesh.vertices.append(xyz)
            if len(mesh.vertices) > MAX_VERTICES:
                raise FormatError('too many vertices')
        elif key == 'f':
            if len(rest) < 3:
                raise FormatError('line %d: face needs at least 3 vertices' % no)
            idx = [_index(t, len(mesh.vertices), no) for t in rest]
            for k in range(1, len(idx) - 1):
                mesh.triangles.append((idx[0], idx[k], idx[k + 1]))
                mesh.materials.append(material)
            if len(mesh.triangles) > MAX_TRIANGLES:
                raise FormatError('too many triangles')
        elif key == 'usemtl':
            material = ' '.join(rest) or None
        elif key in IGNORED:
            continue
        else:
            raise FormatError('line %d: unsupported OBJ statement %r' % (no, key))
    if not mesh.triangles:
        raise FormatError('OBJ has no faces')
    return mesh


def write_obj(mesh, precision=6):
    """Deterministic OBJ text (used for the render-geometry hand-off to the external compiler)."""
    fmt = '{:.%df}' % precision
    out, current = ['# generated by nkgta4; units and axes per the manifest'], object()
    out += ['v ' + ' '.join(fmt.format(c) for c in v) for v in mesh.vertices]
    for (a, b, c), m in zip(mesh.triangles, mesh.materials):
        if m != current:
            out.append('usemtl ' + (m or 'default'))
            current = m
        out.append('f %d %d %d' % (a + 1, b + 1, c + 1))
    return '\n'.join(out) + '\n'
