#!/usr/bin/env python3
"""Generate every page of site/ as static HTML from the data files (standard library only).

    python scripts/build_pages.py                 # rebuild site/ (commit the result)
    python scripts/build_pages.py --check         # exit 1 if the committed site/ differs from a fresh build
    python scripts/build_pages.py --log           # record a What's new entry for data changes, then rebuild
    python scripts/build_pages.py --snapshot      # CI deploy only: render the pets board from site/data/pets-board.json

Also writes robots.txt, sitemap.xml, manifest, favicon, assets/pubs.js, assets/nk.css (from assets/css/*.css),
assets/app.js (from assets/js/*.js), the synced research JSON and site/data/build.json.
"""
import argparse
import datetime as dt
import fnmatch
import importlib
import json
import os
import re
import shutil
import sys
import tempfile
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from nkpages import data as ND  # noqa: E402
from nkpages import routes as NR  # noqa: E402
from nkpages import seo, shell  # noqa: E402

ROOT = ND.ROOT
SITE = ND.SITE
CONFIG = ROOT / "data" / "site.json"
BUILD_JSON = "data/build.json"
# files only a --snapshot (deploy) build writes; gitignored, never listed in build.json
SNAPSHOT_ONLY = ("lost-pets/gh-*", "lost-pets/feed.xml", "data/pets-board.json")
# modules that may define extra_files(D) -> {relpath: str | bytes}
EXTRA_MODULES = ("pages_home", "pages_crime", "pages_pets", "pages_towns", "pages_map",
                 "mapsvg", "search", "changelog", "pets")
PART_BANNER = "/* generated by scripts/build_pages.py from site/assets/{d}/*.{ext}; edit those files, not this one */\n"


class BuildError(Exception):
    pass


def today_ny():
    try:
        from zoneinfo import ZoneInfo
        return dt.datetime.now(ZoneInfo("America/New_York")).date()
    except Exception:
        return dt.date.today()


def load_cfg(path):
    cfg = json.loads(Path(path).read_text(encoding="utf-8"))
    client = (cfg.get("adsense_client") or "").strip()
    if client:
        if not (cfg.get("owner_name") or "").strip():
            raise SystemExit(("About must name who runs the site before ads can be turned on", 2))
        if not shell.ADSENSE_RE.match(client):
            raise SystemExit(("adsense_client must look like ca-pub- followed by 16 digits", 2))
    return cfg


def snapshot_only(rel):
    return any(fnmatch.fnmatch(rel, p) for p in SNAPSHOT_ONLY)


def module(name):
    try:
        return importlib.import_module(f"nkpages.{name}")
    except ModuleNotFoundError as e:
        if e.name == f"nkpages.{name}":
            return None
        raise


def concat(dirname, ext):
    part_dir = SITE / "assets" / dirname
    parts = sorted(part_dir.glob(f"*.{ext}")) if part_dir.exists() else []
    if not parts:
        return None
    out = [PART_BANNER.format(d=dirname, ext=ext)]
    for p in parts:
        out.append(f"\n/* ==== {dirname}/{p.name} ==== */\n")
        out.append(p.read_text(encoding="utf-8").rstrip("\n") + "\n")
    return "".join(out)


def generate(cfg, today, snapshot=False, only=None, keep_going=False, board=None):
    """Returns {relpath: str|bytes} for everything the generator owns."""
    D = ND.load(cfg, today, snapshot=snapshot, board=board)
    routes = NR.resolve(D)
    D["routes"] = routes
    files, problems = {}, []

    for k in ND.SYNCED:
        files[f"data/{k}.json"] = ND.dumps(D[k])
    if snapshot and D["board"] is not None:
        files["data/pets-board.json"] = ND.dumps(D["board"])

    for R in routes:
        if only and R.page not in only and R.path not in only:
            continue
        try:
            mod = module(R.mod)
        except Exception:
            if not keep_going:
                raise
            problems.append(f"{R.path}: importing nkpages.{R.mod} failed: " + traceback.format_exc(limit=2))
            continue
        fn = getattr(mod, R.fn, None) if mod else None
        if fn is None:
            msg = f"{R.path}: nkpages.{R.mod}.{R.fn} is not written yet"
            if keep_going:
                problems.append(msg)
                continue
            raise BuildError(msg)
        try:
            files[R.file] = shell.page_html(D, R, fn(D, R))
        except Exception:
            if not keep_going:
                raise
            problems.append(f"{R.path}: " + traceback.format_exc(limit=3))

    if not only:
        for name in EXTRA_MODULES:
            try:
                mod = module(name)
                hook = getattr(mod, "extra_files", None) if mod else None
                if not hook:
                    continue
                files.update(hook(D) or {})
            except Exception:
                if not keep_going:
                    raise
                problems.append(f"{name}.extra_files: " + traceback.format_exc(limit=3))
        files["robots.txt"] = seo.robots(D)
        files["sitemap.xml"] = seo.sitemap(D, routes)
        files["manifest.webmanifest"] = seo.manifest(D)
        files["favicon.svg"] = seo.favicon()
        files["assets/pubs.js"] = seo.pubs_js()
        a = seo.ads_txt(D)
        if a:
            files["ads.txt"] = a
        css, js = concat("css", "css"), concat("js", "js")
        if css:
            files["assets/nk.css"] = css
        if js:
            files["assets/app.js"] = js
        listed = sorted(f for f in files if not snapshot_only(f))
        files[BUILD_JSON] = json.dumps({"today": today.isoformat(), "files": listed}, indent=0) + "\n"
    for p in problems:
        print("  skipped:", p, file=sys.stderr)
    return files


def _bytes(c):
    return c if isinstance(c, (bytes, bytearray)) else c.encode("utf-8")


def previous_list(site=SITE):
    try:
        return json.loads((site / BUILD_JSON).read_text())["files"]
    except Exception:
        return []


def mirror(out, generated):
    """Make `out` a working copy of site/: every non-generated file symlinked, so links and fetches resolve."""
    skip = set(generated) | set(previous_list())
    for p in SITE.rglob("*"):
        if p.is_dir():
            continue
        rel = p.relative_to(SITE).as_posix()
        if rel in skip or rel.endswith("index.html") or rel == "404.html" or snapshot_only(rel):
            continue
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if not dst.exists() and not dst.is_symlink():
            os.symlink(p, dst)


def write(out, files):
    changed = 0
    for rel, content in files.items():
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        b = _bytes(content)
        if dst.is_symlink():
            dst.unlink()  # never write through a link into site/
        elif dst.exists() and dst.read_bytes() == b:
            continue
        dst.write_bytes(b)
        changed += 1
    return changed


def prune(out, files, prev):
    """Delete generated files that are no longer produced (site/ only)."""
    gone = [f for f in prev if f not in files and not snapshot_only(f)]
    for rel in gone:
        p = out / rel
        if p.exists() and not p.is_symlink():
            p.unlink()
            d = p.parent
            while d != out and d.exists() and not any(d.iterdir()):
                d.rmdir()
                d = d.parent
    if "ads.txt" not in files and (out / "ads.txt").exists():
        (out / "ads.txt").unlink()
        gone.append("ads.txt")
    return gone


def build(out, cfg, today, snapshot=False, only=None, keep_going=False, quiet=False, board=None):
    out = Path(out).resolve()
    files = generate(cfg, today, snapshot=snapshot, only=only, keep_going=keep_going, board=board)
    out.mkdir(parents=True, exist_ok=True)
    if out != SITE.resolve():
        mirror(out, files)
    prev = previous_list(out)
    n = write(out, files)
    gone = prune(out, files, prev) if (out == SITE.resolve() and not only) else []
    if not quiet:
        print(f"built {len(files)} files into {out} ({n} changed, {len(gone)} removed), today={today}")
    return files


def check(cfg):
    prev = previous_list()
    if not prev:
        print("site/data/build.json is missing; run scripts/build_pages.py first")
        return 1
    today = dt.date.fromisoformat(json.loads((SITE / BUILD_JSON).read_text())["today"])
    tmp = Path(tempfile.mkdtemp(prefix="nkcheck-"))
    try:
        files = build(tmp, cfg, today, quiet=True)
        diff = []
        for rel in sorted(set(prev) | {f for f in files if not snapshot_only(f)} | {BUILD_JSON}):
            a, b = SITE / rel, tmp / rel
            if not a.exists() or not b.exists() or a.read_bytes() != b.read_bytes():
                diff.append(rel)
        if diff:
            print("site/ is out of date; run python scripts/build_pages.py. Differs:\n  " + "\n  ".join(diff))
            return 1
        print(f"site/ matches a fresh build ({len(files)} files, today={today})")
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--today", type=dt.date.fromisoformat, default=None)
    ap.add_argument("--out", default=str(SITE))
    ap.add_argument("--config", default=str(CONFIG))
    ap.add_argument("--snapshot", action="store_true")
    ap.add_argument("--board", default=None, help="pets board snapshot for --snapshot (default site/data/pets-board.json)")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--log", action="store_true")
    ap.add_argument("--only", default="", help="comma-separated page ids or paths (development)")
    ap.add_argument("--keep-going", action="store_true", help="skip pages that fail (development)")
    a = ap.parse_args(argv)
    try:
        cfg = load_cfg(a.config)
    except SystemExit as e:
        if isinstance(e.code, tuple):
            print(e.code[0], file=sys.stderr)
            return e.code[1]
        raise
    if a.check:
        return check(cfg)
    today = a.today or today_ny()
    if a.log:
        ch = module("changelog")
        if not ch or not hasattr(ch, "log"):
            print("nkpages.changelog.log is not written yet", file=sys.stderr)
            return 1
        ch.log(ND.load(cfg, today), today)
    only = {s.strip() for s in a.only.split(",") if s.strip()} or None
    build(a.out, cfg, today, snapshot=a.snapshot, only=only, keep_going=a.keep_going, board=a.board)
    return 0


if __name__ == "__main__":
    sys.exit(main())
